enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Messenger]
enabled = false # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[TikTok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
app-name = "Brainrot"
included-patches = "'SIM spoof'"
excluded-patches = "'Disable login requirement'"

[Twitch]
enabled = false # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Music]
enabled = false # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Instagram]
enabled = false # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Reddit]
enabled = true # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Twitter]
enabled = true # whether to build the app. default: true
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
version = "10.49.0-release.0"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom"
app-name = "Lightroom Mobile"
arch = "arm64-v8a"
version = "9.4.1"
included-patches = "'Unlock premium'"
exclusive-patches = true



