logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "auto"
included-patches = "custom-branding external-downloads hdr-auto-brightness hide-ads hide-breaking-news-shelf minimized-playback old-video-quality-menu open-links-externally premium-heading remember-video-quality return-youtube-dislike seekbar-tapping swipe-controls video-ads video-speed custom-video-buffer"
exclusive-patches = true

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
version = "auto"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
version = "5.39.52"
included-patches = "custom-branding-icon-revancify-red"
excluded-patches = "custom-branding-icon-revancify-blue custom-package-name enable-force-minimized-player enable-force-shuffle enable-landscape-mode enable-zen-mode hide-carousel-shelf hide-cast-button hide-category-bar hide-navigation-label hide-new-playlist-button hide-playlist-card hide-taste-builder microg-support remember-video-quality share-button-hook spoof-app-version"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "auto"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
version = "auto"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
version = "auto"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
version = "auto"

